### PR TITLE
Add Fluent toolbar icons and option

### PR DESCRIPTION
**Pull request by AerospaceDoe**
FluentLight
FluentDark
FluentOption

CompareFluent

Both dark and light variants to match the Fluent UI toolbar icons in Notepad++.

### CODE REVIEW

**Comment by pnedev** [comment]
Hi Yaron,

Thank you for the support and for the quick reaction. I appreciate your help and commitment :+1: 
I'll try the icons you provided and write back.

BR

**Comment by Yaron10** [comment]
👍 
My pleasure. :)

Best of luck.

**Comment by AerospaceDoe** [comment]
Sorry for my late reply. 

I see that @Yaron10 has done the work.  Thanks a lot 😄

**Comment by pnedev** [comment]
@Yaron10 , @AerospaceDoe ,

Just tested Yaron's icons and they worked perfectly!
I removed the dedicated icons theme setting from ComparePlus's settings dialog - the icons are automatically switched based on Notepad++'s settings.

The latest code changes are in my `dev` branch and the corresponding dev build is at https://ci.appveyor.com/project/pnedev/compare-plugin/builds/43726568 - choose the platform and you can get the plugin DLL from the Artifacts tab as usual.

Thank you both once again for helping with the icons, great job! :+1: 

BR

**Pull request merged**
